import {
  Building2,
  CarFront,
  GraduationCap,
  HeartPulse,
  Landmark,
  Stethoscope,
  BriefcaseBusiness,
} from "lucide-react";

export const loanCatalog = [
  {
    id: "education",
    name: "Education Loan",
    shortName: "Education",
    description: "Plan tuition, education expenses, and a structured application journey.",
    detail: "Available now",
    status: "available",
    icon: GraduationCap,
    tone: "blue",
    href: "#loan-products",
    applyLabel: "Apply for education loan",
  },
  {
    id: "study-abroad",
    name: "Study Abroad",
    shortName: "Study Abroad",
    description: "Explore a dedicated education-finance journey for international study.",
    detail: "Education journey",
    status: "available",
    icon: Landmark,
    tone: "violet",
    href: "#loan-products",
    applyLabel: "Explore education options",
  },
  {
    id: "personal",
    name: "Personal Loan",
    shortName: "Personal",
    description: "A future-ready product space for personal financial needs.",
    detail: "Coming soon",
    status: "coming-soon",
    icon: BriefcaseBusiness,
    tone: "indigo",
    href: "#loan-products",
  },
  {
    id: "medical",
    name: "Medical Loan",
    shortName: "Medical",
    description: "A future product journey for planned healthcare expenses.",
    detail: "Coming soon",
    status: "coming-soon",
    icon: Stethoscope,
    tone: "teal",
    href: "#loan-products",
  },
  {
    id: "vehicle",
    name: "Vehicle Loan",
    shortName: "Vehicle",
    description: "A future financing journey for eligible vehicle purchases.",
    detail: "Coming soon",
    status: "coming-soon",
    icon: CarFront,
    tone: "orange",
    href: "#loan-products",
  },
  {
    id: "business",
    name: "Business Loan",
    shortName: "Business",
    description: "A future product for business funding and working-capital needs.",
    detail: "Coming soon",
    status: "coming-soon",
    icon: Building2,
    tone: "green",
    href: "#loan-products",
  },
  {
    id: "home",
    name: "Home Loan",
    shortName: "Home",
    description: "A future home-finance journey designed around property goals.",
    detail: "Coming soon",
    status: "coming-soon",
    icon: Landmark,
    tone: "cyan",
    href: "#loan-products",
  },
  {
    id: "healthcare",
    name: "Healthcare Finance",
    shortName: "Healthcare",
    description: "A future category for planned healthcare financing needs.",
    detail: "Coming soon",
    status: "coming-soon",
    icon: HeartPulse,
    tone: "rose",
    href: "#loan-products",
  },
];

export const searchItems = [
  ...loanCatalog.map((loan) => ({
    id: `loan-${loan.id}`,
    type: "Loan",
    label: loan.name,
    description: loan.description,
    href: loan.href,
    icon: loan.icon,
    tone: loan.tone,
    keywords: `${loan.name} ${loan.shortName} loan finance`,
  })),
  {
    id: "tool-emi",
    type: "Tool",
    label: "EMI Calculator",
    description: "Estimate a monthly repayment using amount, rate, and tenure.",
    href: "/emi-calculator",
    icon: Landmark,
    tone: "cyan",
    keywords: "emi calculator monthly payment repayment interest",
  },
  {
    id: "tool-eligibility",
    type: "Tool",
    label: "Check Eligibility",
    description: "Review the information you may need before starting an application.",
    href: "#eligibility",
    icon: GraduationCap,
    tone: "green",
    keywords: "eligibility eligible requirements apply",
  },
  {
    id: "guide-apply",
    type: "Guide",
    label: "How It Works",
    description: "Understand the journey from choosing a product to review.",
    href: "#how-it-works",
    icon: BriefcaseBusiness,
    tone: "blue",
    keywords: "how it works application process steps",
  },
  {
    id: "guide-documents",
    type: "Guide",
    label: "Required Documents",
    description: "Understand why documents are part of the loan application journey.",
    href: "#faq",
    icon: Landmark,
    tone: "violet",
    keywords: "documents kyc required papers application",
  },
  {
    id: "support",
    type: "Support",
    label: "Help & FAQs",
    description: "Find answers about applications, documents, and repayment.",
    href: "#faq",
    icon: HeartPulse,
    tone: "orange",
    keywords: "support help faq questions",
  },
];

export const loanTone = {
  blue: {
    icon: "bg-blue-50 text-blue-700",
    active: "border-blue-200 bg-blue-50/80",
    dot: "bg-blue-500",
  },
  violet: {
    icon: "bg-violet-50 text-violet-700",
    active: "border-violet-200 bg-violet-50/80",
    dot: "bg-violet-500",
  },
  indigo: {
    icon: "bg-indigo-50 text-indigo-700",
    active: "border-indigo-200 bg-indigo-50/80",
    dot: "bg-indigo-500",
  },
  teal: {
    icon: "bg-teal-50 text-teal-700",
    active: "border-teal-200 bg-teal-50/80",
    dot: "bg-teal-500",
  },
  orange: {
    icon: "bg-orange-50 text-orange-700",
    active: "border-orange-200 bg-orange-50/80",
    dot: "bg-orange-500",
  },
  green: {
    icon: "bg-emerald-50 text-emerald-700",
    active: "border-emerald-200 bg-emerald-50/80",
    dot: "bg-emerald-500",
  },
  cyan: {
    icon: "bg-cyan-50 text-cyan-700",
    active: "border-cyan-200 bg-cyan-50/80",
    dot: "bg-cyan-500",
  },
  rose: {
    icon: "bg-rose-50 text-rose-700",
    active: "border-rose-200 bg-rose-50/80",
    dot: "bg-rose-500",
  },
};
